name: "dev pipieline"
on: workflow_dispatch
permissions:
  id-token: write 
  contents: read
jobs: 
  terraform-job:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
       
      - name: Login to AWS
        uses: KoalaOps/login-aws@v1.0.0
        with:
          aws_region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          
        
    
  
